config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  devise_for :users
  unauthenticated :user do
    root to: 'users#index'
  end
  # get 'splash/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: 'pictures#index', as: :authenticated_root
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :pictures

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'splash#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  has_one_attached :photo

  validates :user_id, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :pictures

  # validates :name, presence: true
  validates :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[show edit update destroy]

  # GET /pictures or /pictures.json
  def index
    @user = current_user
    @pictures = current_user.pictures
  end

  # GET /pictures/1 or /pictures/1.json
  def show; end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # POST /pictures or /pictures.json
  def create
    @picture = current_user.pictures.create(picture_params)
    if @picture.save
      flash[:notice] = 'Picture was successfully created'
    else
      flash.now[:notice] = 'Failed'
    end
    redirect_to root_path
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:notice] = 'Picture destroyed successfully'
    redirect_to root_path
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def picture_params
    params.require(:picture).permit(:title, :description, :user_id, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageGalleryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
      <%= yield %>
   
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, class: "contents") do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 border p-2">
    <%= form.label "Add picture" %>
    <%= form.file_field :photo %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "create rounded-lg py-3 px-5 btn flex font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div class="carte">
<%= link_to picture_path(picture.id) do%>
<div id="<%= dom_id picture %>">

  <% if picture.photo.attached? %>
    <img class="img-pic" src="<%=(url_for(picture.photo))%>">
  <% end %>
  <p class="my-2">
    <strong class="block font-medium mb-1">Title: <%= picture.title %> </strong>
  </p>
  <p class="my-2" class="block font-medium mb-1">Description: <%= picture.description %></p>

</div>
<% end%>
</div>

app/views/pictures/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing picture</h1>

  <%= render "form", picture: @picture %>

  <%= link_to "Show this picture", @picture, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pictures", pictures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pictures/index.html.erb
<div class="back-header">
  <div class="back">
      <a class="link" href="/"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
      </svg></a>
  </div>
  <%= link_to '<p class="img-upload">Upload picture</p><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
  <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
  <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
</svg>'.html_safe, new_picture_path %>
  <p class= "out"><%= link_to "Sign out", destroy_user_session_path, class: "sign-out", method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<div class="container w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex-col mt-4 justify-between items-center">
    <h1 class="font-bold text-4xl text-center">Welcome to Ngeni GalleryApp</h1>
    <%= image_tag("galleryappLogo.png", class: "m-auto", id: "logo") %>
  </div>

  <div id="pictures" class="gap-4 min-w-full">
    <%= render @pictures %>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="back-header">
  <div class="back">
      <a class="link" href="/pictures"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
      </svg></a>
  </div>
  <h2 class="mt-3">My Picture</h2>
  <p class= "out"><%= link_to "Sign out", destroy_user_session_path, class: "sign-out", method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-center mt-2">New picture</h1>

  <%= render "form", picture: @picture %>

</div>

app/views/pictures/show.html.erb
<div class="back-header">
  <div class="back">
      <a class="link" href="/pictures"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
      </svg></a>
  </div>
  <h2 class="mt-3">My Picture</h2>
  <p class= "out"><%= link_to "Sign out", destroy_user_session_path, class: "sign-out", method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<div class="mx-auto md:w-2/3 w-full flex mt-4">
  <div class="img-all mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @picture %>

    <div class="inline-block ml-2 mt-1">
      <%= button_to 'Delete this picture', picture_path(@picture), method: :delete, class: "delete mt-2 rounded-lg py-3 px-5 font-medium" %>
    </div>
    <%= link_to 'Back to pictures', pictures_path, class: "back ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/splash/index.html.erb
<div class="container">
	<div class="is-flex justify-content-center">
    <%= image_tag("galleryappLogo.png", class: "m-auto", id: "gallery-logo") %>
    <div>
      <p class="text-center">Welcome to Ngeni.io Gallery-App</p>
    </div>
	</div>
	<div class="btn-1 flex flex-col">
		<%= link_to 'Log in', new_user_session_url, class: "btn log-in" %>
	  <%= link_to 'Sign up', new_user_registration_url, class: "btn log-out" %>
	</div>
</div>

app/views/users/index.html.erb
<div class="splash container mt-4">
	<div class="is-flex justify-content-center">
    <%= image_tag("galleryappLogo.png", class: "m-auto", id: "gallery-logo") %>
	</div>
	<div class="btn-1 flex flex-col gap-2">
		<%= link_to 'Log in', new_user_session_url, class: "btn log-in" %>
	  <%= link_to 'Sign up', new_user_registration_url, class: "btn log-out" %>
	</div>
</div>